sudo: false
language: python
matrix:
  include:
    - python: 3.6
      env: TOXENV=py36
    - python: 3.6
      env: TOXENV=pypi-lint
    - python: 3.6
      env: TOXENV=codestyle
    - python: 3.7
      dist: xenial
      sudo: true
      env: TOXENV=py37

install: pip install tox
before_script: cp tests/config-travisci.py config.py
script: tox

# notification for gitter integration
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/788e94bb42a75aa2df4c
    on_success: always  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: true     # default: false
deploy:
- provider: pypi
  user: gbin
  password:
    secure: xyzABC123
  distributions: bdist_wheel
  on:
    condition: $TOXENV = lint
- provider: pypi
  user: gbin
  password:
    secure: xyzABC123
  distributions: bdist_wheel
  on:
    condition: $TOXENV = lint
    tags: true
